export const labels = {
    logIn: 'Sign in',
    signUp: 'Sign Up',
    from:'From',
    to:'To',
    invoiceCreationandEditing: 'Invoice Creation & Editing',
    clientManagementandInvoiceTracking: 'Client Management , Invoice Tracking',
    powerfulReportingandAnalytics: 'Powerful Reporting & Analytics',
    message1: 'Intuitive interface for creating and editing invoices, With automatic invoice numbering and ability to add line items with descriptions, quantities, rates, and taxes, Support for multiple currencies.',
    message2: 'Client database to store and manage client information. Link clients to their respective invoices. Option to add new clients and manage   existing ones.',
    message3: 'Generate reports on invoicing trends, revenue, and outstanding payments. Analytics dashboard for financial insights, Export reports in various formats (PDF, CSV).',
    welcomeBack: 'Welcome Back',
    loginMessage: 'Login to access your account',
    email: 'Email',
    no:'No',
    yes:'Yes',
    password: 'Password',
    emailAddress: 'Email Address',
    enterEmail: 'Enter Email',
    enterPassword: 'Enter Password',
    back: 'Back',
    products: 'Products',
    product: 'Product',
    services: 'Services',
    categories: 'Categories',
    units: 'Units',
    totalProducts: 'Total Products',
    addNewProduct: 'Add New Product',
    addNewCategory: 'Add New Category',
    addNewUnits: 'Add New Units',
    productName: 'Product Name',
    productCode: 'Product Code(SKU)',
    productCategory: 'Product Category',
    sellingPrice: 'Selling Price',
    purchasePrice: 'Purchase Price',
    discountType: 'Discount Type',
    discountValue: 'Discount Value',
    barCode: 'Barcode',
    alertQuantity: 'Alert Quantity',
    tax: 'Tax',
    enterProductName: 'Enter Product Name',
    enterProductCode: 'Enter Product Code',
    generateCode: 'Generate Code',
    chooseCategory: 'Choose Category',
    addSellingPrice: 'Add Selling Price',
    enterPurchasePrice: 'Enter Purchase Price',
    select: 'Select',
    selectDate: 'Select Date',
    enterDiscountValue: 'Enter Discount Value',
    enterBarcode: 'Enter Barcode ',
    enterAlertQuantity: 'Enter Alert Quantity',
    selectItemsTax: 'Select Item’s Tax',
    saveChanges: 'Save Changes',
    apply:'Apply',
    reset: 'Reset',
    enterCategorySlug: 'Enter Category Slug',
    enterSlug: 'Enter  Slug',
    name: 'Name',
    slug: 'Slug',
    symbol: 'Symbol',
    enterUnitName: 'Enter Unit Name',
    enterSymbol: 'Enter Symbol',
    stockIn: 'Stock In',
    stockOut: 'Stock Out',
    addedSuccessfully: 'Added Successfully',
    removedSuccessfully: 'Removed Successfully',
    stockAddedSuccessMsg: 'Stock has been added to the inventory successfully',
    backToInventory: 'Back to Inventory',
    dashboard: 'Dashboard',
    yourTotalBalance: 'Your Total Balance',
    addAQuick: 'Add a Quick',
    paymentStatics: 'Payment Statics',
    totalInvoiceAmount: 'Total Invoice Amount',
    frequentCustomers: 'Frequent Customers',
    seeAll: 'See all',
    quickAccess: 'Quick Access',
    customers: 'Customers',
    customer: 'Customer',

    invoices: 'Invoices',
    salesReturn: 'Sales Return',
    quotation: 'Quotation',
    quotationId: 'Quotation ID',
    quotationReport: 'Quotation Report',
    quotationsbyLast30Days: 'Quotations by Last 30 Days',
    vendors: 'Vendors',
    vendor: 'Vendor',

    deliveryChallan: 'Delivery Challan',
    creditNote: 'Credit Note',
    payments: 'Payments',
    purchase: 'Purchase',
    purchases: 'Purchases',
addPurchase:'Add Purchase',
purchaseDetails:'Purchases Details',
    purchaseReturn: 'Purchase Return',
    purchaseReturnReport: 'Purchase Return Report',
    purchaseOrders: 'Purchase Orders',
    purchaseOrderDetails: 'Purchase Orders Details',
    inventory: 'Inventory',
    expense: 'Expense',
    expenses: 'Expenses',
    templates: 'templates',
    signatures: 'Signatures',
    invoiceStatics: 'Invoice Statics',
    paid: 'Paid',
    sent: 'sent',
    drafted: 'Drafted',
    partiallypaid: 'Partially Paid',
    overDue: 'Overdue',
    recentInvoice: 'Recent Invoices',
    viewAll: 'View All',
    amount: 'Amount',
    modeOfPayment: 'Mode of Payment',
    dueDate: 'Due Date',
    paymentSummary: 'Payment Summary',
    paymentSummaryText: 'View the Payment Summary on your Invoices',
    viewSummary: 'View Summary',
    recentCustomers: 'Recent Customers',
    addInvoice: 'Add Invoice',
    addNew: 'Add New',
    beatsPro: 'Beats pro',
    pc: 'PC',
    quantity: "Quantity",
    addQuantity: 'Add Quantity',
    editProduct: 'Edit product',
    cancel: 'Cancel',
    removeQuanity: 'Remove Quantity',
    searchInventory: 'Search Inventory',
    searchCustomer : 'Search Customer',
    searchQuotations : 'Search Quotations',
    searchDeliveryChallan : 'Search Delivery Challan',
    searchPayments : 'Search Payments',
    searchCreditNotes : 'Search Credit Notes',
    customerImage: 'Customer Image',
    sizeOfImg1: 'Size Should be below 4 MB,',
    sizeOfImg2: 'Size Should be below 800*400px,',
    sizeOfImg3: 'Size Should be below 100*100px,',
    companyIcon: 'Company Icon',
    companyName: 'Company Name',
    enterCompanyName: 'Enter Company Name',
    companyEmail: 'Company Email',
    enterCompanyEmail: 'Enter Company Email',
    adminSmith: 'Admin Smith',
    settings: 'Settings',
    darkMode: 'Dark Mode',
    generalSettings: 'General Settings',
    invoiceSettings: 'Invoice Settings',
    invoiceTemplates: 'Invoice Templates',
    bankDetails: 'Bank Details',
    taxRates: 'Tax Rates',
    rate: 'Rate',
    discountAmnt: 'Discount Amount',
    logout: 'Logout',
    accountsettings: 'Account Settings',
    basicDetails: 'Basic Details',
    changePassword: 'Change Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobileNumber: 'Mobile Number',
    gender: 'Gender',
    dateofBirth: 'Date of Birth',
    chooseDate: 'Choose Date',
    chooseGender: 'Choose Gender',
    enterMobileNumber: 'Enter Mobile Number',
    enterLastName: 'Enter Last Name',
    enterFirstName: 'Enter First Name',
    oldPassword: 'Old Password',
    enterOldPassword: 'Enter Old Password',
    enterNewPassword: 'Enter New Password',
    enterConfirmPassword: 'Enter Confirm Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    mainLogo: 'Main Logo',
    addressInfo: 'Address Info',
    addressLine1: 'Address Line 1',
    addressLine2: 'Address Line 2',
    enterAddress: 'Enter Address',
    country: 'Country',
    state: 'State',
    city: 'City',
    pinCode: 'Pincode',
    enterCountry: 'Enter Country',
    chooseState: 'Choose State',
    chooseCity: 'Choose City',
    enterPincode: 'Enter Pincode',
    invoicePrefix: 'Invoice Prefix',
    enterInvoicePrefix: 'Enter Invoice Prefix',
    invoiceLogo: 'Invoice Logo',
    bankAccounts: ' Bank Accounts',
    accName1: 'Emily',
    accNum1: '54213236132',
    bankName1: 'Federal Bank',
    branch1: 'Brooklyn',
    IFSCode1: '65485',
    accountNumber: 'Account Number : ',
    accountNumber1: 'Account Number',
    bankName: 'Bank Name',
    branch: 'Branch',
    ifsc: 'IFSC Code',
    addBankDetails: 'Add Bank Details',
    accountHolderName: 'Account Holder Name',
    branchName: 'Branch Name',
    taxRate: 'Tax Rate : ',
    addTax: 'Add Tax ',
    taxName: 'Tax Name',
    type: 'Type',
    chooseType: 'Choose Type',
    expenseReport: 'Expense Report',
    purchaseReport: 'Purchase Report',
    reports: 'Reports',
    fedex: 'FedEX',
    abbott:'Abbott',
    whirlpool:'Whirlpool',
    fedexEmail: 'fedx@example.com',
    category: 'Category',
    createdOn: 'Created On',
    marketing: 'Marketing',
    date1: '15 Mar 2024',
    amount1: '$1500',
    google: 'Google',
    googleEmail: 'google@example.com',
    software: 'Software',
    date2: '10 Mar 2024',
    amount2: '$1100',
    worldEnergy: 'World Energy',
    worldEmail: 'worldenergy@example.com',
    amount3: '$990',
    advertising: 'Advertising',
    date3: '26 Feb 2024',
    paloatte: 'Paloatte',
    paloatteEmail: 'paloatte@example.com',
    date4: '18 Feb 2024',
    pending: 'Pending',
    expensesByLast30Days: 'Expenses by Last 30 Days',
    purchasesByLast30Days: 'Purchases by Last 30 Days',
    purchaseQuantity: 'Purchase Quantity : ',
    purchaseQty: 'Purchase Qty',
    inStockQty: 'Instock Qty',
    salesReturnbyLast30Days: 'Sales Return by Last 30 Days',
    sales: 'Sales',
    salesbyLast30Days: 'Sales by Last 30 Days',
    soldQty: 'Sold Qty',
    instockQuantity: 'Instock Quantity : ',
    paymentReport: 'Payment Report',
    paymentsbyLast30Days: 'Payments by Last 30 Days',
    paymentReceived: 'Payment Received',
    paymentSent: 'Payment Sent',
    netPayment: 'Net Payment',
    stocksbyLast30Days: 'Stocks by Last 30 Days',
    lowstocksbyLast30Days: 'Low Stocks by Last 30 Days',
    stocks: 'Stocks',
    openingQty: 'Opening Qty',
    qtyIn: 'Qty In',
    qtyOut: 'Qty Out',
    closingQty: 'Closing Qty',
    stockReport: 'Stock Report',
    lowStocks: 'Low Stocks',
    lowStocksReport: 'Low Stocks Report',
    openingQuantity: 'Opening Quantity',
    closingQuantity: 'Closing Quantity',
    incomeReport: 'Income Report',
    incomebyLast30Days: 'Income by Last 30 Days',
    income: 'Income',
    incomeAmount: 'Income Amount',
    date: 'Date',
    taxReport: 'Tax Report',
    purchaseTax: 'Purchase tax',
    salesTax: 'Sales Tax',
    taxByLast30days: 'taxByLast30days',
    emily: 'Emily',
    jerry: 'Jerry',
    peter: 'Peter',
    lisa: 'Lisa',
    andrew:'Andrew',
    discount: 'Discount',
    taxAmount: 'Tax Amount',
    totalAmnt: 'Total Amount',
    creditNotes: 'Credit Notes',
    addSignature: 'Add Signature',
    enterSignatureName: 'Enter Signature Name',
    signatureName: 'Signature Name',
    markAsDefault: 'Mark as default',
    unpaid: 'Unpaid',
    draft: 'Draft',
    allInvoices: 'All Invoices',
    referenceNumber: 'Reference Number',
    enterReferenceNumber: 'Enter Reference Number',
    invoiceDate: 'Invoice Date',
    enterInvoiceDate: 'Enter Invoice Date',
    eneterDueDate: ' Enter Due Date',
    customerName: 'Customer Name',
    enterCustomerName: 'Enter Customer Name',
    paymentMethod: 'Payment Method',
    enterPaymentMethod: 'Enter Payment Method',
    selectBank: 'Select Bank',
    notes: 'Notes',
    termsConditions: 'Terms & Conditions',
    terms: 'Terms',
    selectSignature: 'Select Signature',
    continue: 'Continue',
    searchProducts: 'Search Products',
    createNewProduct: 'Create New Product',
    productCodeSKU: 'Product Code (SKU)',
    reference: 'Reference',
    addExpense: 'Add Expense',
    paymentMode: 'Payment Mode',
    expenseDate: 'Expense Date',
    paymentStatus: 'Payment Status',
    attachment: 'Attachment',
    bryan: 'Bryan',
    addVendor: 'Add Vendor',
    closingBalance: 'Closing Balance',
    enterBalanceAmount: 'Enter Balance Amount',
    phoneNumber: 'Phone Number',
    ledger: 'Ledger',
    ledgers: 'Ledgers',
    vendorDetails: 'Vendor Details',
    phone: 'Phone',
    debit: 'Debit',
    credit: 'Credit',
    addLedger: 'Add Ledger',
    purchaseOrderID: ' Purchase Order ID',
    purchaseOrder: 'Purchase Order',
    addpurchaseReturn: 'Add Purchase Return',
    addPurchaseOrder: 'Add Purchase Order',
    vendorName: 'Vendor Name',
    purchasesOrderDate: 'Purchases Order Date',
    forgetPassword: 'Forget Password ?',
    enterYourEmailtogetapasswordresetlink: 'Enter your email to get a password reset link',
    resetPassword: 'Reset Password',
    rememberYourPassword: 'Remember your password?',
    general: 'General',
    receipt: 'Receipt',
    supplierInvoiceSerialNumber:'Supplier Invoice Serial Number',
    addCustomer: 'Add Customer',
    address: 'Address',
    enterName: 'Enter Name',
    enterEmailAddress: 'Enter Email Address',
    enterPhone: 'Enter Phone',
    website: 'Website',
    addWebsite: 'Add Website',
    next: 'Next',
    prev: 'Prev',
    billingAddress: 'Billing Address',
    shippingAddress: 'Shipping Address',
    enterCity: 'Enter City',
    enterState: 'Enter State',
    pincode: 'Pincode',
    enterBankName: 'Enter Bank Name',
    enterBranch: 'Enter Branch',
    enterAccountHolderName: 'Enter Account Holder Name',
    enterAccountNumber: 'Enter Account Number',
    enterIfsc: 'Enter IFSC',
    customerDetails: 'Customer Details',
    quotations: 'Quotations',
    addQuotations: 'Add Quotations',
    quotationDate: 'Quotation Date',
    quotationDetails: 'Quotation Details',
    invoiceDetails: 'Invoice Details',
    invoice: 'Invoice',
    deliveryChallans: 'Delivery Challans',
    addDeliveryChallan: 'Add Delivery Challan',
    deliveryChalanDate: 'Delivery Challan Date',
    deliveryChallanDetails: 'Delivery Chalan Details',
    addCreditNote: 'Add Credit Note',
    creditNoteDate: 'Credit Note Date',
    creditNotesDetails : 'Credit Notes Details', 
    menu : 'Menu',
   
    SendPaymentLink : 'Send Payment Link',
    paymentLinkSuccessfully : 'Payment Link Successfully',
    backToInvoice : 'Back to Invoice',
  
    purchaseOrderNo: 'Purchase Order No',
    purchaseOrderTo: 'Purchase Order To',
    venderName:'Vender Name',
    purchasesDate:'Purchases Date',
    debitNotesDetails:'Debit Notes Details',
    debitNoteNo:'Debit Note No',
    addSalesReturn:'Add Sales Return',
    salesReturnDate:'Sales Return Date',
    salesReturnDetails:'Sales Return Details',
    notification:'Notifications',
    markallasRead:'Mark all as read',
    deleteAllNotifications:'Delete All Notifications',
    filter:'Filter',
    profitorLoss:'Profit or Loss',
    stripeSales:'Stripe Sales',
    exchangeGainorLoss:'Exchange Gain or Loss',
    stripeFees:'Stripe Fees'
    // add your labels below
}