export const screenName = {
    DashboardScreen: 'Dashboard',
    OnboardingScreen: 'Onboarding',
    LoginEmailScreen: "LoginEmailScreen",
    Products: 'Products',
    AddNewProducts: 'AddNewProduct',
    AddNewCategories: 'AddNewCategories',
    AddNewUnits: 'AddNewUnits',
    InventoryList: 'InventoryList',
    InventoryAdded: 'InventoryAdded',
    InventoryRemoved: 'InventoryRemoved',
    InvoiceScreen: 'Invoice',
    ReportsScreen: 'Reports',
    SettingsScreen: 'Settings',
    AddInvoiceScreen: 'AddInvoice',
    AccountSettings: 'AccountSettings',
    GeneralSettings: 'GeneralSettings',
    InvoiceSettings: 'InvoiceSettings',
    BankDetails: 'BankDetails',
    TaxRate: 'TaxRate',
    InvoiceTemplates: 'InvoiceTemplates',
    ExpenseReport: 'ExpenseReport',
    PurchaseReport: 'PurchaseReport',
    PurchaseReturnReport: 'PurchaseReturnReport',
    SalesReport: 'SalesReport',
    SalesReturnReport: 'SalesReturnReport',
    QuotationReport: 'QuotationReport',
    PaymentReport: 'PaymentReport',
    StockReport: 'StockReport',
    LowStockReport: 'LowStockReport',
    IncomeReport: 'IncomeReport',
    TaxReport: 'TaxReport',
    PurchaseTaxReport: 'PurchaseTaxReport',
    Signatures: 'Signatures',
    AddSignatures: 'AddSignatures',
    InvoiceTemplatesScreen: 'InvoiceTemplatesScreen',
    ProductScreen: 'Product',
    CustomersScreen: 'Customers',
    AddCustomersScreen: 'AddCustomer',
    AddExpenses: 'AddExpenses',
    ExpensesScreen: 'ExpensesScreen',
    ViewExpenses: 'ViewExpenses',
    VendorDetails: 'VendorDetails',
    AddLedger: 'AddLedger',
    AddVendor: 'AddVendor',
    LedgersScreen: 'LedgersScreen',
    VendorsScreen: 'VendorsScreen',
    PurchaseOrderScreen:'PurchaseOrderScreen',
    AddPurchaseOrderScreen:'AddPurchaseOrderScreen',
    ForgetPassword:'ForgetPassword',
    CustomerDetails : 'Customer Details',
    QuotationsScreen : 'QuotationsScreen',
    AddQuotationScreen : 'AddQuotationScreen',
    QuotationDetails : 'QuotationDetails',
    PaymentsScreen : 'PaymentsScreen',
    InvoiceDetailsScreen : 'InvoiceDetailsScreen',
    DeliverChallanScreen : 'DeliverChallanScreen',
    AddDeliveryScreen : 'AddDeliveryScreen',
    DeliveryChallanDetails : 'DeliveryChallanDetails',
    CreditNotesScreen : 'CreditNotesScreen',
    AddCreditNotesScreen : 'AddCreditNotesScreen',
    CreditNotesDetailsScreen : 'CreditNotesDetailsScreen',
    SendPaymentLink : 'SendPaymentLink',
    SuccessSendPaymentLink : 'SuccessSendPaymentLink',
    AddInvoiceOption : 'AddInvoiceOption',
 
    PurchaseOrderDetails: 'PurchaseOrderDetails',
    PurchaseReturn: 'PurchaseReturn',
    AddPurchaseReturn: 'AddPurchaseReturn',
    PurchaseReturnDebitNotesDetails: 'PurchaseReturnDebitNotesDetails',
    Purchases: 'Purchases',
    AddPurchases: 'AddPurchases',
    PurchasesDetails: 'PurchasesDetails',
    SalesReturn: "SalesReturn",
    AddSalesReturn: "AddSalesReturn",
    SalesReturnDetails: "SalesReturnDetails",
    NotificationScreen:'NotificationScreen',
    ProfitorLoss:'ProfitorLoss',
    PaymentSummary:'PaymentSummary'
};